import "./globals.css";
import { Fira_Sans } from "next/font/google";

const firaSans = Fira_Sans({ subsets: ["latin"], weight: ["300", "400" , "700"] });

export const metadata = {
  title: "Task List",
  description:
    "A front-end application for managing tasks and to-do lists.Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={firaSans.className}>{children}</body>
    </html>
  );
}
